export const HEADER_LINKS = [
  { href: "/", label: "Home" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/about-us", label: "About Us" },
  { href: "/contact", label: "Contact" },
];

export const FOOTER_ICON_SIZE = 32;

export const FOOTER_LINKS = [
  {
    href: "https://www.instagram.com/pacomojica/",
    src: "/youtube.svg",
    alt: "YouTube Mojica Bricks",
  },
  {
    href: "https://www.instagram.com/pacomojica/",
    src: "/facebook.svg",
    alt: "Facebook Mojica Bricks",
  },
  {
    href: "https://www.instagram.com/pacomojica/",
    src: "/instagram.svg",
    alt: "Instagram Mojica Bricks",
  },
];

export const GRID_CATEGORIES = [
  'All',
  'Cats',
  'Dogs',
  'Horses',
];

export const PROJECTS = [
  {
    name: 'Zeus',
    cover: '/projects/zeus/pexels-pixabay-161758.jpg',
    coverWidth: 4480,
    coverHeight: 5600,
    images: [],
    categories: ['Cats', 'Horses', 'Dogs'],
    description: 'Zeus is the sky and thunder god in ancient Greek religion and mythology, who rules as king of the gods on Mount Olympus. His name is cognate with the first syllable of his Roman equivalent Jupiter',
    status: 'Completed',
  },
  {
    name: 'Apollo',
    cover: '/projects/apollo/pexels-jimmy-chan-1309897.jpg',
    coverWidth: 4559,
    coverHeight: 3269,
    images: [],
    categories: ['Cats'],
    description: 'Apollo is one of the Olympian deities in classical Greek and Roman religion and Greek and Roman mythology. Apollo has been recognized as a god of archery, music and dance, truth and prophecy, healing and diseases, the Sun and light, poetry, and more',
    status: 'In progress',
  },
  {
    name: 'Ares',
    cover: '/projects/ares/pexels-tyler-hendy-52062.jpg',
    coverWidth: 4000,
    coverHeight: 2661,
    images: [],
    categories: ['Horses'],
    description: 'Ares is the Greek god of war and courage. He is one of the Twelve Olympians, and the son of Zeus and Hera. The Greeks were ambivalent towards him. He embodies the physical valor necessary for success in war but can also personify sheer brutality and bloodlust, in contrast to his sister Athena, whose martial functions include military strategy and generalship',
    status: 'Completed',
  },
  {
    name: 'Artemis',
    cover: '/projects/artemis/pexels-pixabay-462205.jpg',
    coverWidth: 3179,
    coverHeight:
      4223,
    images: [],
    categories: ['Horses'],
    description: 'Artemis is the goddess of the hunt, the wilderness, wild animals, nature, vegetation, childbirth, care of children, and chastity.[1][2] In later times, she was identified with Selene, the personification of the Moon.[3] She was often said to roam the forests and mountains, attended by her entourage of nymphs. The goddess Diana is her Roman equivalent',
    status: 'In progress',
  },
  {
    name: 'Athena',
    cover: '/projects/athena/pexels-expect-best-323780.jpg',
    coverWidth: 5264,
    coverHeight: 3393,
    images: [],
    categories: ['Horses', 'Cats'],
    description: 'Athena or Athene, often given the epithet Pallas, is an ancient Greek goddess associated with wisdom, warfare, and handicraft[3] who was later syncretized with the Roman goddess Minerva.[4] Athena was regarded as the patron and protectress of various cities across Greece, particularly the city of Athens, from which she most likely received her name',
    status: 'Completed',
  },
  {
    name: 'Demeter',
    cover: '/projects/demeter/pexels-luis-ruiz-1774931.jpg',
    coverWidth: 4000,
    coverHeight: 6000,
    images: [],
    categories: ['Cats', 'Dogs'],
    description: 'Demeter is the Olympian goddess of the harvest and agriculture, presiding over crops, grains, food, and the fertility of the earth. Although Demeter is mostly known as a grain goddess, she also appeared as a goddess of health, birth, and marriage, and had connections to the Underworld',
    status: 'In progress',
  },
  {
    name: 'Hades',
    cover: '/projects/hades/pexels-joshua-135018.jpg',
    coverWidth: 4709,
    coverHeight: 3141,
    images: [],
    categories: ['Horses', 'Dogs'],
    description: "Hades, in the ancient Greek religion and mythology, is the god of the dead and the king of the underworld, with which his name became synonymous. Hades was the eldest son of Cronus and Rhea, although this also made him the last son to be regurgitated by his father. He and his brothers, Zeus and Poseidon, defeated their father's generation of gods, the Titans, and claimed joint rulership over the cosmos",
    status: 'Completed',
  },
  {
    name: 'Hephaestus',
    cover: '/projects/hephaestus/pexels-yentl-jacobs-157811.jpg',
    coverWidth: 5107,
    coverHeight: 3405,
    images: [],
    categories: ['Horses'],
    description: "Hephaestus is the Greek god of artisans, blacksmiths, carpenters, craftsmen, fire, metallurgy, metalworking, sculpture and volcanoes. Hephaestus's Roman counterpart is Vulcan. In Greek mythology, Hephaestus was either the son of Zeus and Hera or he was Hera's parthenogenous child",
    status: 'In progress',
  },
  {
    name: 'Hera',
    cover: '/projects/hera/pexels-aleksandar-pasaric-325185.jpg',
    coverWidth: 5472,
    coverHeight: 3648,
    images: [],
    categories: ['Dogs'],
    description: "Hera is the goddess of marriage, women, and family, and the protector of women during childbirth. In Greek mythology, she is queen of the twelve Olympians and Mount Olympus, sister and wife of Zeus, and daughter of the Titans Cronus and Rhea",
    status: 'Completed',
  },
  {
    name: 'Hermes',
    cover: '/projects/hermes/pexels-pixasquare-com-1115804.jpg',
    coverWidth: 3024,
    coverHeight: 3024,
    images: [],
    categories: ['Dogs'],
    description: "Hermes is an Olympian deity in ancient Greek religion and mythology considered the herald of the gods. He is also considered the protector of human heralds, travelers, thieves,[2] merchants, and orators.[3][4] He is able to move quickly and freely between the worlds of the mortal and the divine aided by his winged sandals",
    status: 'Completed',
  },
  {
    name: 'Hestia',
    cover: '/projects/hestia/pexels-scott-webb-1029611.jpg',
    coverWidth: 3847,
    coverHeight: 5583,
    images: [],
    categories: ['Dogs'],
    description: "In ancient Greek religion and mythology, Hestia is the virgin goddess of the hearth and the home. In myth, she is the firstborn child of the Titans Cronus and Rhea, and one of the Twelve Olympians",
    status: 'In progress',
  },
  {
    name: 'Poseidon',
    cover: '/projects/poseidon/pexels-pixabay-262367.jpg',
    coverWidth: 3888,
    coverHeight: 2430,
    images: [],
    categories: ['Cats'],
    description: "Poseidon is one of the Twelve Olympians in ancient Greek religion and mythology, presiding over the sea, storms, earthquakes and horses. He was the protector of seafarers and the guardian of many Hellenic cities and colonies. In pre-Olympian Bronze Age Greece, Poseidon was venerated as a chief deity at Pylos and Thebes, with the cult title 'earth shaker' in the myths of isolated Arcadia, he is related to Demeter and Persephone and was venerated as a horse, and as a god of the waters",
    status: 'Completed',
  },
];

export const SLIDES = [
  { src: '/images/slider/pexels-pixabay-327482.jpg', width: 2782, height: 1455, title: 'Residential Horses', callToAction: 'View more', href: '/portfolio/Horses' },
  { src: '/images/slider/pexels-pixabay-417273.jpg', width: 5184, height: 3456, title: 'Interior Dogs', callToAction: 'View more', href: '/portfolio/Dogs' },
  { src: '/images/slider/pexels-pixabay-534174.jpg', width: 3543, height: 2365, title: 'Retail Cats', callToAction: 'View more', href: '/portfolio/Cats' },
]

export const PROJECT_COVERS = [
  { label: 'Cats', src: '/portfolio/pexels-julia-kuzenkov-1974596.jpg', width: 3024, height: 4032, },
  { label: 'Dogs', src: '/portfolio/pexels-pixabay-534247.jpg', width: 3456, height: 5184, },
  { label: 'Horses', src: '/portfolio/pexels-ricky-esquivel-1662159.jpg', width: 3769, height: 4711, },
];

export const TEAM = [
  { name: "Cody Kerr", cover: "/team/pexels-alexander-suhorucov-6457488.jpg", coverWidth: 5000, coverHeight: 3333, },
  { name: "Jayden Arias", cover: "/team/pexels-alexander-suhorucov-6457493.jpg", coverWidth: 5000, coverHeight: 3333, },
  { name: "Jayda Walls", cover: "/team/pexels-alexander-suhorucov-6457515.jpg", coverWidth: 5000, coverHeight: 3333, },
  { name: "Kyle Sharp", cover: "/team/pexels-alexander-suhorucov-6457537.jpg", coverWidth: 5000, coverHeight: 3333, },
  { name: "Kylie Baxter", cover: "/team/pexels-alexander-suhorucov-6457544.jpg", coverWidth: 5000, coverHeight: 3333, },
  { name: "Micah Mathews", cover: "/team/pexels-alexander-suhorucov-6457562.jpg", coverWidth: 5000, coverHeight: 3333, },
];

export const bluredDataURLs = {
  '/compare/download-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQH/8QAIBAAAAYCAgMAAAAAAAAAAAAAAAECBAUSAxEhIjFBYf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDUJOWnlODW0TgLDsqoUfr6K0zrqpWZJtrnuXkABJ//2Q==',
  '/compare/pexels-binyamin-mellish-106399-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAHhAAAQQCAwEAAAAAAAAAAAAAAQACAwQFIREiQWH/xAAVAQEBAAAAAAAAAAAAAAAAAAABBP/EABgRAQEBAQEAAAAAAAAAAAAAAAECAAMh/9oADAMBAAIRAxEAPwDcv5e7JaeIoYooweoO9fVUZ2AAB1ZxPvBRFRfbpKEuKiX1N//Z',
  '/images/pexels-alex-staudinger-1732414-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAID/8QAHxAAAQMEAwEAAAAAAAAAAAAAAgABAwQFBxESFCEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAZEQADAQEBAAAAAAAAAAAAAAABAgMAIjL/2gAMAwEAAhEDEQA/ALxzla6R24qWrBqkQHfKR9ut5chylKZdKL13f4iKVKMh5OSzV/Q3/9k=',
  '/images/pexels-gdtography-911738-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUH/8QAGxABAAMAAwEAAAAAAAAAAAAAAQACAwQhImH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A3/ffPOpZPLJ7bhKrTt+RED//2Q==',
  '/images/pexels-gdtography-911758-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIH/8QAHhAAAQMEAwAAAAAAAAAAAAAAAQACAwQFETEhIlH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANZNut1PdRMyPMgGdcBW+vw49zvxERH/2Q==',
  '/portfolio/pexels-julia-kuzenkov-1974596-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAANAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgf/xAAiEAABAwMFAAMAAAAAAAAAAAABAgMRAAQFBhITIVEHMkL/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABgRAAMBAQAAAAAAAAAAAAAAAAABEQID/9oADAMBAAIRAxEAPwCsZ7WdtZ6eOWsIcecTIaJ7E+1Oh8oZ1QChwAHuNhpY3jrdFkLfYFRJClCTPtBX8Armci+d+x/I9qXTTUCH/9k=',
  '/portfolio/pexels-pixabay-534247-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgIF/8QAJhAAAQMDAwIHAAAAAAAAAAAAAQIDBAAFBhESQRMUITEyQlFhcf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAFxEBAQEBAAAAAAAAAAAAAAAAAREAAv/aAAwDAQACEQMRAD8ANN3a4ZNjqRbY22Q+8GUAD2cqrSRfbxFQmOqHuUyOmT86eFHoOWriYwh2ysiO6yvtmj9Hn9qxkkoABxO5Y9R18zzQGiwNSOiFXf/Z',
  '/portfolio/pexels-ricky-esquivel-1662159-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAMAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwUHCP/EAB8QAAICAgMAAwAAAAAAAAAAAAECAwQFEQAGIUFxcv/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEv/aAAwDAQACEQMRAD8AruT73j6OSigtWQjyeBR7r744HaICBqSLX65lTC5a1beBrRWZnk2zONk8FazN1bMoWYgByAB8e8TBOrZ//9k=',
  '/project/pexels-aleksandar-pasaric-1758672-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQG/8QAHxAAAQMEAwEAAAAAAAAAAAAAAQACBAMFBxESEyEy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABgRAQADAQAAAAAAAAAAAAAAAAEAAgMx/9oADAMBAAIRAxEAPwDAW7LV6pwWc+t72ED58KtOYZezuFT2iJGlx7C5UTk//9k=',
  '/project/pexels-binyamin-mellish-186077-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAHxAAAQQCAgMAAAAAAAAAAAAAAQACAwQREhMhFBUx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAZEQACAwEAAAAAAAAAAAAAAAAAAQIRMVH/2gAMAwEAAhEDEQA/ANKzPfZIyPhhrnXOjDkFXN8stB9TXPX3kHaIqucr1idcP//Z',
  '/project/pexels-expect-best-323772-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAIRAAAQMDBAMAAAAAAAAAAAAAAQACAwQFEQYHCCEyQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECESExQf/aAAwDAQACEQMRAD8AjduQDrtcJI4jU09EOmiEYd8JKyHd7V4OIpacxjxLm9kesoiSWrCS48n/2Q==',
  '/project/pexels-igor-starkov-1117452-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAEAAQQDAQAAAAAAAAAAAAABAAIDBAUREiFS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAaEQACAgMAAAAAAAAAAAAAAAABAwAEESEx/9oADAMBAAIRAxEAPwCis4Wsw8gtXKFfOUJT06XUtI9n0+WIiZcdnsuumoaAn//Z',
  '/project/pexels-jean-van-der-meulen-1457844-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAPAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABv/EAB4QAAEDBQEBAAAAAAAAAAAAAAECBBEAAwUGEjEh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AEuW3R6x2Esk225HSOelfVdU/D9zAkiaG5rVcW5eWso4sFbpJEK6jzym1loo2bZEQUg04n//2Q==',
  '/project/pexels-life-of-pix-14613-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUH/8QAIRAAAQQBAwUAAAAAAAAAAAAAAQACBAURAwYHEhMhMXH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AqUV5sp2z74UUCVpQBjvdXs/FlTtbjpziTHnZJyfBREH/2Q==',
  '/project/pexels-photo-1633970-blur.jpeg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQG/8QAIBAAAQMCBwAAAAAAAAAAAAAAAQADBgQRAgUSEyIxYv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwCKHTKnYpizgy4bQ6OrktaJ7YWDT4A9BEUyD//Z',
  '/project/pexels-pixabay-210158-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUG/8QAHxAAAQMDBQAAAAAAAAAAAAAAAwABEQIEBRITISMx/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AKGDBiacKYJgO53brqjxY81hY7tcjadTzwiJC//Z',
  '/project/pexels-pixabay-258160-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIH/8QAHRAAAgICAwEAAAAAAAAAAAAAAQMAAgQFBhExUv/EABUBAQEAAAAAAAAAAAAAAAAAAAUG/8QAGBEAAwEBAAAAAAAAAAAAAAAAAQIDABH/2gAMAwEAAhEDEQA/AJ2fOsR/GXqZjqpb57mRM3qiy5CKdEk+xEccmbcGn5ItV6w3/9k=',
  '/project/pexels-pixabay-276724-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEG/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIAAwUEBhESFDFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAEDESH/2gAMAwEAAhEDEQA/AJvnF1juGpY1cqeen39mAqzNKVIp0FDFQASR5iIE3jZTTuH/2Q==',
  '/project/pexels-scott-webb-1029606-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQH/8QAHhABAAEDBQEAAAAAAAAAAAAAAQADBxECBAUGYoP/xAAVAQEBAAAAAAAAAAAAAAAAAAAEBf/EABgRAAIDAAAAAAAAAAAAAAAAAAABAhMU/9oADAMBAAIRAxEAPwDSC6vXs5dG4fmygufwSCUK+HzERlaJWmZ//9k=',
  '/project/pexels-tirachard-kumtanom-347141-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAYH/8QAHxAAAQQBBQEAAAAAAAAAAAAAAQACAwQhBQYREyIx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAaEQADAAMBAAAAAAAAAAAAAAABAgMABBES/9oADAMBAAIRAxEAPwDZxqNyaK5VjibgeXud9KhJbW4xI8CnXI5Oe0IiUi0l8oeZNsSSx64z/9k=',
  '/team/pexels-alexander-suhorucov-6457488-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQH/8QAIBAAAQQBBAMAAAAAAAAAAAAAAgABAwQFBgchURESIv/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGhEAAQUBAAAAAAAAAAAAAAAAAQACAwQREv/aAAwDAQACEQMRAD8Auz+5cmawNuvWOQJLZMR+W4j7ZlnhaaCUnkezyT+z/PaIp9qQtcMR7Z5wYv/Z',
  '/team/pexels-alexander-suhorucov-6457493-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAHhAAAQMEAwAAAAAAAAAAAAAAAgABEQMEBQYSE0H/xAAVAQEBAAAAAAAAAAAAAAAAAAADBf/EABgRAQADAQAAAAAAAAAAAAAAAAEAAgMh/9oADAMBAAIRAxEAPwDPb1smT24gub0gEBbi4g0SyhSxVp1BDVYhvURT7WVib51E5P/Z',
  '/team/pexels-alexander-suhorucov-6457515-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAhEAABBAAGAwAAAAAAAAAAAAABAAIDBQQGBxESIRMxYf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AIllqJeyY6eQ2EjWMnB8ZG/E/FYGoWd3Ddli3iex0PSIhDWVcL//2Q==',
  '/team/pexels-alexander-suhorucov-6457537-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAfEAACAgIBBQAAAAAAAAAAAAABAwACBBEFEhQhUWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAAxFR/9oADAMBAAIRAxEAPwCPtDlc8sruKpY2zBcDRqR6kr7MDmbymE9R86+xEJaVwxDay4Byf//Z',
  '/team/pexels-alexander-suhorucov-6457544-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUG/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIAAwQFEQYxEyFB/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABcRAAMBAAAAAAAAAAAAAAAAAAABAjL/2gAMAwEAAhEDEQA/AJfCchWzufvaKOVQP5GHRYD5N618isV2fR11EQdZQqdM/9k=',
  '/team/pexels-alexander-suhorucov-6457562-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMH/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIAEQQDBTEGFBUhI//EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAZEQACAwEAAAAAAAAAAAAAAAAAAgEDITH/2gAMAwEAAhEDEQA/AK47Hyuya5Ut3a/Rro0OBNHHUu2oApxTa+uIiAi5kjBrVq/T/9k=',
  '/images/slider/pexels-pixabay-327482-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAFAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUG/8QAHBAAAgIDAQEAAAAAAAAAAAAAAQIABAMRIRVR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwDG0rzjFbCogyMuxk11dfJK9SweluxEcAhVv//Z',
  '/images/slider/pexels-pixabay-417273-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAYH/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIABAUGAxETMXH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABoRAQADAAMAAAAAAAAAAAAAAAEAAgMRITH/2gAMAwEAAhEDEQA/AJHMZ7T7GuctfAYo1TwsAGdeyw+zPm2GurFR5gAevcRJ0DXu55DEceSiz//Z',
  '/images/slider/pexels-pixabay-534174-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUG/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIAAwQFEQYUIkFx/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABkRAQACAwAAAAAAAAAAAAAAAAEAEQISIf/aAAwDAQACEQMRAD8Aj63rjX42nsoxca0WkcVOx5ZR9mGu3NDWuzdyWLEnz9xEZzdQuBXZ/9k=',
  '/projects/apollo/pexels-jimmy-chan-1309897-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAHhAAAAYCAwAAAAAAAAAAAAAAAAECAwURBBIhMTL/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIDABFB/9oADAMBAAIRAxEAPwDcrk8lUcZYmpOK87dCjZTRtotbF0V8AAJOjB3APubRVCqeb//Z',
  '/projects/ares/pexels-tyler-hendy-52062-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMH/8QAHBAAAQQDAQAAAAAAAAAAAAAAAQADBBECBSFB/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAaEQEAAgMBAAAAAAAAAAAAAAABAhEAA5ES/9oADAMBAAIRAxEAPwDLtZP1QYt6LkczdKR3DNmo3POoiHGB6k29yg7UCq5n/9k=',
  '/projects/artemis/pexels-pixabay-462205-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgUH/8QAIRAAAQMEAgMBAAAAAAAAAAAAAgEDBAAFBhEhURITIkH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABwRAAICAgMAAAAAAAAAAAAAAAIRAAMBBAUSIf/aAAwDAQACEQMRAD8AGYnZnX4cqTNlkjUZNp61/a0iNj12cjtG3f5aAQIop0muKUu4TZ7dZJrMNogF0Nrst81MjJKbjNAMsvEQRE+ekqmusCFv1xj5TaEl2eJ//9k=',
  '/projects/athena/pexels-expect-best-323780-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAHhAAAgEEAwEAAAAAAAAAAAAAAQIAAwQFBgcRMRP/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABgRAQEBAQEAAAAAAAAAAAAAAAECABED/9oADAMBAAIRAxEAPwCOub1lFv7m5pVnVUJAQ+ATYJy/lAij4Ieh73ES1rXFw85J6G//2Q==',
  '/projects/demeter/pexels-luis-ruiz-1774931-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwYI/8QAIRAAAgICAgEFAAAAAAAAAAAAAQIDBAARBQYHFSEyYpH/xAAVAQEBAAAAAAAAAAAAAAAAAAAEBf/EABkRAAIDAQAAAAAAAAAAAAAAAAECAAMEEf/aAAwDAQACEQMRAD8AtPJU60+BSijATWjrX1wSehp2Gh7HND9u6R69NFyEdlklgXQjPxIwUtwLFamjJO0dl/DjKrSxPZJ05wgXk//Z',
  '/projects/hades/pexels-joshua-135018-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUH/8QAHxAAAgMAAAcAAAAAAAAAAAAAAQIAAwQFERQhIzFR/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABcRAQEBAQAAAAAAAAAAAAAAAAERAAL/2gAMAwEAAhEDEQA/AMqy14dGLq76PIBzKj0xktuOFWKrUoA7AfIiK4Ktwu2BN//Z',
  '/projects/hephaestus/pexels-yentl-jacobs-157811-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAfEAACAgEEAwAAAAAAAAAAAAABAwACBQQGERIiMZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Aks9e6dzahNDwtJ6io9SmThFMSu5qPKoP0RED/9k=',
  '/projects/hera/pexels-aleksandar-pasaric-325185-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAYH/8QAHhAAAgIBBQEAAAAAAAAAAAAAAQIAAwUEBhESISL/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACEv/aAAwDAQACEQMRAD8A3B9dWyW9Kl5UeSGt3RkFtcDH0EAkD7iInSRuS//Z',
  '/projects/hermes/pexels-pixasquare-com-1115804-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgUH/8QAHxAAAQMEAwEAAAAAAAAAAAAAAQIDBAAFERIGIUGB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAaEQABBQEAAAAAAAAAAAAAAAABAAIDESEE/9oADAMBAAIRAxEAPwBhbLvYp8lxpGrDRQUJV7tWfS+JXAyniia+UbqwdfM1c4s02eFyHC2jcSU4VjsfaWJJwOzUs/SbFi0jha0Zi//Z',
  '/projects/hestia/pexels-scott-webb-1029611-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAPAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAABAUGB//EACQQAAEDAgQHAAAAAAAAAAAAAAECAwQABQYRIXESFCMxMkGS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwX/xAAdEQACAgEFAAAAAAAAAAAAAAABBAACEQMGEhMx/9oADAMBAAIRAxEAPwC6wjje14oZCCtMaZ7bWe+1Pyy3meoj6FYJcpNqg3BLMSGWnwcypJy4dqPE99QB5h3XXyNLZoUOBLCe2mGNPsueOfJ//9k=',
  '/projects/poseidon/pexels-pixabay-262367-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQH/8QAHxAAAQQCAgMAAAAAAAAAAAAAAQACAwQFIRESEzFR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL62bms4mWKEeB7m6e32FlNiC4bEp7xHlx2SfqIg/9k=',
  '/projects/zeus/pexels-pixabay-161758-blur.jpg': 'data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAcEAEAAgMAAwAAAAAAAAAAAAABAAMCBBEGEjH/xAAUAQEAAAAAAAAAAAAAAAAAAAAG/8QAHBEAAQMFAAAAAAAAAAAAAAAAAQACIQMEERIx/9oADAMBAAIRAxEAPwCB3tW11btunEys9mwDvOfJE+RgoUHCIh8VjqDgSkD7dnJX/9k=',
}
